### PR TITLE
fixed small typos in LN_SKEW

### PR DESCRIPTION
**Pull request by srikash**
standard deviation file was called as SETEV (should be STDEV) and output filename was setdev (should be stdev).

### CODE REVIEW

**Comment by layerfMRI** [comment]
Thanks @Sri. Lets include this. 

@ofgulban as you know, I had included some fixed in LN_SKEW in devel few months ago regarding NaN's.
And we are always trying to keep the master brach identical to the latest release. Do you know a way to merge this in devel without resulting in conflicts? 
Otherwise we just wait until the next release.

**Comment by ofgulban** [comment]
thanks @srikash for the pull request. @layerfMRI there are no conflicts, I have now merged your `devel` branch changes and sri's changes in `master` branch. These changes will be automatically included in the next LayNii release.

**Comment by layerfMRI** [comment]
Thanks 🙏. 
I think this means we should release this version soon. I was told that it is customary to have the master branch match the code of the latest release. Which might be helpful for the upcoming workshops too. Let me know, if I should release this version.

**Comment by ofgulban** [comment]
I have bumped the version to 2.5.2 and made a pre release. Feel free to add binaries as zip files

**Comment by layerfMRI** [comment]
Binaries are added now. Feel free to release it.

**Pull request merged**
