### PR TITLE
[FIX] fix version number

### LINKED ISSUE #56: Laynii version number in 'Citation.cff'
Hi LayNii developers,

the Citation.cff contains `version: 2.1.0 `, whereas the correct one is `v.2.2.1` as indicated in the Zenodo integration: [https://zenodo.org/record/6351766#.YtWoL3ZBy8w](url)

All the best,
Alessandra

### PR DESCRIPTION
**Pull request by Remi-Gau**
- fixes version number in citation.cff (closes #56)
- remove unsolved merge conflicts (mentioned in #60)
- fix citation cff to make it valid and add github action to ensure it will stay valid
- add a `bump_version` recipe in the makefile to automate version changes:
  - it takes the version from [dep/laynii_lib.cpp](https://github.com/layerfMRI/LAYNII/blob/0f0e835199db6808bf02acf13caa79614e3822f4/dep/laynii_lib.cpp) as the single, unambiguous, authoritative representation of the version number and updates citation.cff with it.

### CODE REVIEW

**Comment by Remi-Gau** [comment]
@layerfMRI this should fix the issue you mentioned

**Comment by ofgulban** [comment]
@Remi-Gau , thanks for the PR. I am a bit worried about making the `citation.cff` as "ground truth". Can you explain what this does?

**Comment by Remi-Gau** [comment]
Well you want to only change the version number in one place and update all the other instances automatically.

Maybe there is a best practice of where this metadata is stored for cpp codebase but I don't know about it. If there is I am happy to do it some other way. 

The advantage of the citation.cff file is that it has the metadata for your code, is used by zenodo when making a release on github, adds a "how to cite" on the github page of your repo and has a schema that can ensure the citation file is valid.

**Comment by ofgulban** [comment]
I understand the version number consistency and do follow it in my other projects. However, in LayNii, our ground truth is written at https://github.com/layerfMRI/LAYNII/blob/0f0e835199db6808bf02acf13caa79614e3822f4/dep/laynii_lib.cpp .

So I would be curious to figure out how this can be made the reference point for the other auxiliary scripts & processes.

**Comment by ofgulban** [comment]
Thanks for all your effort. I am only half focusing on this right now, but I am going to check the commits. Thanks for your effort.

**Comment by Remi-Gau** [comment]
> Thanks for all your effort. I am only half focusing on this right now, but I am going to check the commits.

no rush

**Comment by ofgulban** [comment]
I had double checked with Renzo, our plan is to make the 2.3.0 release in 16th Jan week (after OHBM deadline). Hopefully we, thanks to your PR too, we can have an improved release workflow.

**Comment by ofgulban** [comment]
Thanks @Remi-Gau , merged I am going to create the v2.3.0 release right now.

**Pull request merged**
